FLASH_CARD_KNOWLEDGE = 10
FLASH_CARD_INSPIRATION = 20
FLASH_CARD_TIMER = 30
FLASH_CARD_COMMEMORATE = 40

FLASH_CARD_TYPE_LIST = [
    FLASH_CARD_KNOWLEDGE,
    FLASH_CARD_INSPIRATION,
    FLASH_CARD_TIMER,
    FLASH_CARD_COMMEMORATE
]
